name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm test

    - name: Install SAP CDS Development Kit
      run: npm install -g @sap/cds-dk


    - name: Build Project
      run: cds build

    - name: Deploy to SQLite
      run: cds deploy --to sqlite:db/test.db
